exclude: tests/fixtures

repos:
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        language_version: python3.11.13
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3.11.13
  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        args: [--max-line-length=240, --extend-ignore=E203]
  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: bash -c 'cd frontend && npx prettier . --write'
        language: system
        files: \.(js|vue|css|html|json)$
        exclude: node_modules/|dist/
