services:
  backend:
    image: ${ECR_REPO_URI}
    container_name: rpg-encounters-backend
    env_file:
      - .env
    environment:
      # LLMs
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEFAULT_MODEL_TEMP=${DEFAULT_MODEL_TEMP}
      - DEFAULT_MODEL_NAME=${DEFAULT_MODEL_NAME}
      # TTS
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
      - GOOGLE_CLOUD_TTS_API_KEY=${GOOGLE_CLOUD_TTS_API_KEY}
      - DEFAULT_TTS_PROVIDER=${DEFAULT_TTS_PROVIDER}
      # DB
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      # TELEMETRY
      - LANGFUSE_TRACING_ENABLED=${LANGFUSE_TRACING_ENABLED}
      - LANGFUSE_PUBLIC_KEY=${LANGFUSE_PUBLIC_KEY}
      - LANGFUSE_SECRET_KEY=${LANGFUSE_SECRET_KEY}
      - LANGFUSE_HOST=${LANGFUSE_HOST}
      # System
      - ENVIRONMENT=${ENVIRONMENT} # local, production
      - SERVICE=${SERVICE}
      - FRONTEND_URL=${FRONTEND_URL}
      - GIT_SHA=${GIT_SHA}
      - ECR_REPO_URI=${ECR_REPO_URI}
      - GRPC_VERBOSITY=${GRPC_VERBOSITY}
      - AWS_REGION=${AWS_REGION}
      # Moderation
      - SKIP_MODERATION=${SKIP_MODERATION}
      - OPEN_AI_MODERATION_THRESHOLD=${OPEN_AI_MODERATION_THRESHOLD}
      # Session management
      - SESSION_SECRET_KEY=${SESSION_SECRET_KEY}
      # HTTPS Configuration (disabled for local development)
      - USE_HTTPS=${USE_HTTPS}
      # Transcription
      - TRANSCRIPTION_POOL_SIZE=${TRANSCRIPTION_POOL_SIZE}
      # Email
      - LOG_MAGIC_LINK=${LOG_MAGIC_LINK} # For getting raw login token and avoid email
      - SEND_EMAIL=${SEND_EMAIL}
      - SES_IDENTITY=${SES_IDENTITY}
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - rpg-network
    restart: unless-stopped

  db:
    image: postgres
    restart: always
    container_name: rpg-encounters-data
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - /data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - rpg-network

  adminer:
    container_name: rpg-encounters-adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - rpg-network

networks:
  rpg-network:
    driver: bridge
