/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/auth/request': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Request Magic Link
     * @description Request a magic link for login. Account must already exist.
     *     Sets device_nonce cookie for device binding.
     *     Returns empty 200 response to prevent user enumeration.
     */
    post: operations['request_magic_link_api_auth_request_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Consume Magic Link
     * @description Consume a magic link token to create a user session and redirect to destination.
     *     Requires matching device_nonce cookie.
     *     Token is provided as a query parameter.
     */
    get: operations['consume_magic_link_api_auth_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/check': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Check Auth
     * @description Check if user is authenticated via session.
     */
    get: operations['check_auth_api_auth_check_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/logout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Logout
     * @description Logout by destroying the session
     */
    post: operations['logout_api_auth_logout_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/profile': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Profile */
    get: operations['get_profile_api_profile_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/players': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Players
     * @description Get all players
     */
    get: operations['get_players_api_players_get']
    put?: never
    /**
     * Create Player
     * @description Create a new player
     */
    post: operations['create_player_api_players_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/players/{player_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Player
     * @description Get a specific player by ID
     */
    get: operations['get_player_api_players__player_id__get']
    /**
     * Update Player
     * @description Update an existing player
     */
    put: operations['update_player_api_players__player_id__put']
    post?: never
    /**
     * Delete Player
     * @description Delete a player
     */
    delete: operations['delete_player_api_players__player_id__delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/players/{player_id}/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Consume Player Login
     * @description Consume a player magic link token to create a player session
     */
    get: operations['consume_player_login_api_players__player_id__login_get']
    put?: never
    /**
     * Request Player Login
     * @description Generate a magic link for player login
     */
    post: operations['request_player_login_api_players__player_id__login_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/players/{player_id}/encounter': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Player Encounter
     * @description Get the encounter assigned to the current player with character details
     */
    get: operations['get_player_encounter_api_players__player_id__encounter_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/characters': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Characters
     * @description Get all characters
     */
    get: operations['get_characters_api_characters_get']
    put?: never
    /**
     * Create Character
     * @description Create a new character and generate AI content in background
     */
    post: operations['create_character_api_characters_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/characters/{character_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Character
     * @description Get a specific character by ID
     */
    get: operations['get_character_api_characters__character_id__get']
    /**
     * Update Character
     * @description Update an existing character and regenerate AI content in background if needed
     */
    put: operations['update_character_api_characters__character_id__put']
    post?: never
    /**
     * Delete Character
     * @description Delete a character
     */
    delete: operations['delete_character_api_characters__character_id__delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/memories': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get All Memories
     * @description Get all memories across all characters
     */
    get: operations['get_all_memories_api_memories_get']
    put?: never
    /**
     * Create Memory
     * @description Create a memory for multiple characters
     */
    post: operations['create_memory_api_memories_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/memories/{memory_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Memory
     * @description Get a specific memory by ID
     */
    get: operations['get_memory_api_memories__memory_id__get']
    /**
     * Update Memory
     * @description Update a memory
     */
    put: operations['update_memory_api_memories__memory_id__put']
    post?: never
    /**
     * Delete Memory
     * @description Delete a memory
     */
    delete: operations['delete_memory_api_memories__memory_id__delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/reveals': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get All Reveals
     * @description Get all reveals across all characters
     */
    get: operations['get_all_reveals_api_reveals_get']
    put?: never
    /**
     * Create Reveal
     * @description Create a reveal for multiple characters
     */
    post: operations['create_reveal_api_reveals_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/reveals/{reveal_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Reveal
     * @description Get a specific reveal by ID
     */
    get: operations['get_reveal_api_reveals__reveal_id__get']
    /**
     * Update Reveal
     * @description Update a reveal
     */
    put: operations['update_reveal_api_reveals__reveal_id__put']
    post?: never
    /**
     * Delete Reveal
     * @description Delete a reveal
     */
    delete: operations['delete_reveal_api_reveals__reveal_id__delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/reveals/character/{character_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Character Reveals
     * @description Get all reveals for a character
     */
    get: operations['get_character_reveals_api_reveals_character__character_id__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/encounters/{encounter_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Encounter
     * @description Get a specific encounter by ID
     */
    get: operations['get_encounter_api_encounters__encounter_id__get']
    /**
     * Update Encounter
     * @description Update an existing encounter
     */
    put: operations['update_encounter_api_encounters__encounter_id__put']
    post?: never
    /**
     * Delete Encounter
     * @description Delete an encounter
     */
    delete: operations['delete_encounter_api_encounters__encounter_id__delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/encounters/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Create Encounter
     * @description Create a new encounter
     */
    post: operations['create_encounter_api_encounters__post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/encounters/connections': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Create Connection
     * @description Create a new connection between encounters
     */
    post: operations['create_connection_api_encounters_connections_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/encounters/connections/{connection_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /**
     * Update Connection
     * @description Update an existing connection
     */
    put: operations['update_connection_api_encounters_connections__connection_id__put']
    post?: never
    /**
     * Delete Connection
     * @description Delete a connection
     */
    delete: operations['delete_connection_api_encounters_connections__connection_id__delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/encounters/{encounter_id}/connections': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Encounter Connections
     * @description Get all connections for a specific encounter
     */
    get: operations['get_encounter_connections_api_encounters__encounter_id__connections_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/encounters/{encounter_id}/conversation/{player_id}/{character_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Conversation Data
     * @description Get current influence and reveals data for a player/character combination
     */
    get: operations['get_conversation_data_api_encounters__encounter_id__conversation__player_id___character_id__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/canvas': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Canvas
     * @description Get complete canvas state - all encounters with connections
     */
    get: operations['get_canvas_api_canvas_get']
    put?: never
    /**
     * Save Canvas
     * @description Save entire canvas state - handles new, existing, and deleted items
     */
    post: operations['save_canvas_api_canvas_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/game/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Game Data
     * @description Get all game data constants for frontend caching
     */
    get: operations['get_game_data_api_game__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/voices/tts_providers': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Tts Providers
     * @description Get available TTS providers for the current user
     */
    get: operations['get_tts_providers_api_voices_tts_providers_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/voices/search': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Search Voices
     * @description Search for available voices
     */
    get: operations['search_voices_api_voices_search_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/voices/{voice_id}/sample': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Voice Sample
     * @description Generate and stream a voice sample using static text
     */
    get: operations['get_voice_sample_api_voices__voice_id__sample_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/worlds': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Worlds
     * @description Get all worlds for the current user
     */
    get: operations['get_worlds_api_worlds_get']
    put?: never
    /**
     * Create World
     * @description Create a new world for the current user
     */
    post: operations['create_world_api_worlds_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/worlds/{world_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get World
     * @description Get a specific world by ID
     */
    get: operations['get_world_api_worlds__world_id__get']
    put?: never
    post?: never
    /**
     * Delete World
     * @description Delete a world
     */
    delete: operations['delete_world_api_worlds__world_id__delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** AuthCheckResponse */
    AuthCheckResponse: {
      /**
       * Authenticated
       * @description Whether the user is authenticated
       */
      authenticated: boolean
    }
    /**
     * CanvasResponse
     * @description Response with complete canvas state - same structure as encounters endpoint
     */
    CanvasResponse: {
      /** Encounters */
      encounters: components['schemas']['Encounter'][]
      /** Connections */
      connections: components['schemas']['Connection'][]
    }
    /**
     * CanvasSaveRequest
     * @description Unified request to save entire canvas state
     */
    CanvasSaveRequest: {
      /** New Encounters */
      new_encounters?: components['schemas']['EncounterWithId'][]
      /** Existing Encounters */
      existing_encounters?: components['schemas']['EncounterWithId'][]
      /** New Connections */
      new_connections?: components['schemas']['ConnectionCreate'][]
      /** Existing Connections */
      existing_connections?: components['schemas']['ConnectionUpdate'][]
      /** Deleted Encounter Ids */
      deleted_encounter_ids?: number[]
      /** Deleted Connection Ids */
      deleted_connection_ids?: number[]
    }
    /** Character */
    Character: {
      /**
       * Name
       * @description Character name
       */
      name: string
      /**
       * Race
       * @description Character race
       */
      race: string
      /**
       * Size
       * @description Character size
       */
      size: string
      /**
       * Alignment
       * @description Character alignment
       */
      alignment: string
      /**
       * Gender
       * @description Character gender
       */
      gender: string
      /**
       * Profession
       * @description Character profession
       */
      profession: string
      /**
       * Background
       * @description Character background
       */
      background: string
      /**
       * Communication Style
       * @description Character communication style summary
       * @default
       */
      communication_style: string
      /**
       * Communication Style Type
       * @description Communication style preset
       */
      communication_style_type: string
      /**
       * Motivation
       * @description Character motivation
       */
      motivation: string
      /**
       * Voice Id
       * @description TTS provider voice Id
       */
      voice_id: string
      /**
       * Voice Name
       * @description TTS provider voice name
       * @default Default
       */
      voice_name: string
      /**
       * Tts Provider
       * @description TTS provider
       */
      tts_provider: string
      /**
       * Race Preferences
       * @description Race preferences for influence calculation
       */
      race_preferences?: {
        [key: string]: number
      } | null
      /**
       * Class Preferences
       * @description Class preferences for influence calculation
       */
      class_preferences?: {
        [key: string]: number
      } | null
      /**
       * Gender Preferences
       * @description Gender preferences for influence calculation
       */
      gender_preferences?: {
        [key: string]: number
      } | null
      /**
       * Size Preferences
       * @description Size preferences for influence calculation
       */
      size_preferences?: {
        [key: string]: number
      } | null
      /** Id */
      id: number
    }
    /**
     * CharacterCreate
     * @description Character creation model - inherits all validation from CharacterBase.
     */
    CharacterCreate: {
      /**
       * Name
       * @description Character name
       */
      name: string
      /**
       * Race
       * @description Character race
       */
      race: string
      /**
       * Size
       * @description Character size
       */
      size: string
      /**
       * Alignment
       * @description Character alignment
       */
      alignment: string
      /**
       * Gender
       * @description Character gender
       */
      gender: string
      /**
       * Profession
       * @description Character profession
       */
      profession: string
      /**
       * Background
       * @description Character background
       */
      background: string
      /**
       * Communication Style
       * @description Character communication style summary
       * @default
       */
      communication_style: string
      /**
       * Communication Style Examples
       * @description Communication style examples
       */
      communication_style_examples?: string[] | null
      /**
       * Communication Style Type
       * @description Communication style preset
       */
      communication_style_type: string
      /**
       * Motivation
       * @description Character motivation
       */
      motivation: string
      /**
       * Personality
       * @description AI-generated personality profile for influence scoring
       * @default
       */
      personality: string
      /**
       * Voice Id
       * @description TTS provider voice Id
       */
      voice_id: string
      /**
       * Voice Name
       * @description TTS provider voice name
       * @default Default
       */
      voice_name: string
      /**
       * Tts Provider
       * @description TTS provider
       */
      tts_provider: string
      /**
       * Race Preferences
       * @description Race preferences for influence calculation
       */
      race_preferences?: {
        [key: string]: number
      } | null
      /**
       * Class Preferences
       * @description Class preferences for influence calculation
       */
      class_preferences?: {
        [key: string]: number
      } | null
      /**
       * Gender Preferences
       * @description Gender preferences for influence calculation
       */
      gender_preferences?: {
        [key: string]: number
      } | null
      /**
       * Size Preferences
       * @description Size preferences for influence calculation
       */
      size_preferences?: {
        [key: string]: number
      } | null
    }
    /**
     * CharacterUpdate
     * @description Character update model - all fields optional with same validation rules.
     */
    CharacterUpdate: {
      /** Name */
      name?: string | null
      /** Race */
      race?: string | null
      /** Size */
      size?: string | null
      /** Alignment */
      alignment?: string | null
      /** Gender */
      gender?: string | null
      /** Profession */
      profession?: string | null
      /** Background */
      background?: string | null
      /** Communication Style */
      communication_style?: string | null
      /**
       * Communication Style Examples
       * @description Communication style examples
       */
      communication_style_examples?: string[] | null
      /** Communication Style Type */
      communication_style_type?: string | null
      /** Motivation */
      motivation?: string | null
      /** Personality */
      personality?: string | null
      /** Voice Id */
      voice_id?: string | null
      /** Voice Name */
      voice_name?: string | null
      /** Tts Provider */
      tts_provider?: string | null
      /** Race Preferences */
      race_preferences?: {
        [key: string]: number
      } | null
      /** Class Preferences */
      class_preferences?: {
        [key: string]: number
      } | null
      /** Gender Preferences */
      gender_preferences?: {
        [key: string]: number
      } | null
      /** Size Preferences */
      size_preferences?: {
        [key: string]: number
      } | null
    }
    /** Connection */
    Connection: {
      /**
       * Source Encounter Id
       * @description Source encounter ID (temp UUID or int)
       */
      source_encounter_id: number | string
      /**
       * Target Encounter Id
       * @description Target encounter ID (temp UUID or int)
       */
      target_encounter_id: number | string
      /**
       * Source Handle
       * @description Source connection handle
       */
      source_handle: string
      /**
       * Target Handle
       * @description Target connection handle
       */
      target_handle: string
      /**
       * Edge Type
       * @description Vue Flow edge type
       * @default straight
       */
      edge_type: string
      /**
       * Stroke Color
       * @description Connection line color
       * @default #007bff
       */
      stroke_color: string
      /**
       * Stroke Width
       * @description Connection line width
       * @default 3
       */
      stroke_width: number
      /** Id */
      id: number
    }
    /**
     * ConnectionCreate
     * @description Connection creation model
     */
    ConnectionCreate: {
      /**
       * Source Encounter Id
       * @description Source encounter ID (temp UUID or int)
       */
      source_encounter_id: number | string
      /**
       * Target Encounter Id
       * @description Target encounter ID (temp UUID or int)
       */
      target_encounter_id: number | string
      /**
       * Source Handle
       * @description Source connection handle
       */
      source_handle: string
      /**
       * Target Handle
       * @description Target connection handle
       */
      target_handle: string
      /**
       * Edge Type
       * @description Vue Flow edge type
       * @default straight
       */
      edge_type: string
      /**
       * Stroke Color
       * @description Connection line color
       * @default #007bff
       */
      stroke_color: string
      /**
       * Stroke Width
       * @description Connection line width
       * @default 3
       */
      stroke_width: number
    }
    /**
     * ConnectionUpdate
     * @description Connection update model - all fields optional
     */
    ConnectionUpdate: {
      /** Source Encounter Id */
      source_encounter_id?: number | string | null
      /** Target Encounter Id */
      target_encounter_id?: number | string | null
      /** Source Handle */
      source_handle?: string | null
      /** Target Handle */
      target_handle?: string | null
      /** Edge Type */
      edge_type?: string | null
      /** Stroke Color */
      stroke_color?: string | null
      /** Stroke Width */
      stroke_width?: number | null
      /** Id */
      id?: number | null
    }
    /** ConversationData */
    ConversationData: {
      /**
       * Type
       * @description Data type for websocket listener
       * @default conversation_data
       * @constant
       */
      type: 'conversation_data'
      /**
       * Influence
       * @description Influence score. Can be earned or from D20 roll
       */
      influence: number
      /**
       * Reveals
       * @description Available manipulated reveals with level information
       * @default []
       */
      reveals: {
        [key: string]: unknown
      }[]
    }
    /**
     * DefaultThresholds
     * @description Default threshold values for reveal layers
     */
    DefaultThresholds: {
      /**
       * Standard
       * @description Standard reveal threshold
       */
      standard: number
      /**
       * Privileged
       * @description Privileged reveal threshold
       */
      privileged: number
      /**
       * Exclusive
       * @description Exclusive reveal threshold
       */
      exclusive: number
    }
    /** Encounter */
    Encounter: {
      /**
       * Name
       * @description Encounter name
       */
      name: string
      /**
       * Description
       * @description Encounter description
       */
      description?: string | null
      /**
       * Position X
       * @description X coordinate on the canvas
       */
      position_x: number
      /**
       * Position Y
       * @description Y coordinate on the canvas
       */
      position_y: number
      /**
       * Character Ids
       * @description Character IDs in this encounter
       */
      character_ids?: number[] | null
      /**
       * Player Ids
       * @description Player IDs in this encounter
       */
      player_ids?: number[] | null
      /** Id */
      id: number
    }
    /** EncounterCreate */
    EncounterCreate: {
      /**
       * Name
       * @description Encounter name
       */
      name: string
      /**
       * Description
       * @description Encounter description
       */
      description?: string | null
      /**
       * Position X
       * @description X coordinate on the canvas
       */
      position_x: number
      /**
       * Position Y
       * @description Y coordinate on the canvas
       */
      position_y: number
      /**
       * Character Ids
       * @description Character IDs in this encounter
       */
      character_ids?: number[] | null
      /**
       * Player Ids
       * @description Player IDs in this encounter
       */
      player_ids?: number[] | null
    }
    /**
     * EncounterUpdate
     * @description Encounter update model - all fields optional with same validation rules
     */
    EncounterUpdate: {
      /** Name */
      name?: string | null
      /** Description */
      description?: string | null
      /** Position X */
      position_x?: number | null
      /** Position Y */
      position_y?: number | null
      /** Character Ids */
      character_ids?: number[] | null
      /** Player Ids */
      player_ids?: number[] | null
    }
    /**
     * EncounterWithId
     * @description Encounter model that includes temp ID for canvas save operations
     */
    EncounterWithId: {
      /**
       * Name
       * @description Encounter name
       */
      name: string
      /**
       * Description
       * @description Encounter description
       */
      description?: string | null
      /**
       * Position X
       * @description X coordinate on the canvas
       */
      position_x: number
      /**
       * Position Y
       * @description Y coordinate on the canvas
       */
      position_y: number
      /**
       * Character Ids
       * @description Character IDs in this encounter
       */
      character_ids?: number[] | null
      /**
       * Player Ids
       * @description Player IDs in this encounter
       */
      player_ids?: number[] | null
      /** Id */
      id: number | string
    }
    /**
     * GameDataResponse
     * @description Complete game data response containing all constants for frontend caching
     */
    GameDataResponse: {
      /**
       * Races
       * @description Available character races
       */
      races: string[]
      /**
       * Classes
       * @description Available character classes
       */
      classes: string[]
      /**
       * Alignments
       * @description Available character alignments
       */
      alignments: string[]
      /**
       * Skills
       * @description Available character skills
       */
      skills: string[]
      /**
       * Communication Styles
       * @description Available communication styles
       */
      communication_styles: string[]
      /** @description Size options for different entities */
      sizes: components['schemas']['SizeOptions']
      /**
       * Difficulty Classes
       * @description Difficulty class values
       */
      difficulty_classes: {
        [key: string]: number
      }
      /** @description Default reveal thresholds */
      default_thresholds: components['schemas']['DefaultThresholds']
      /** @description Text and character limits */
      validation_limits: components['schemas']['ValidationLimits']
      /** @description Threshold configuration limits */
      threshold_limits: components['schemas']['ThresholdLimits']
      /** @description Ability and skill modifier limits */
      modifier_limits: components['schemas']['ModifierLimits']
      /**
       * Tts Providers
       * @description Available TTS providers
       */
      tts_providers: string[]
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /** MagicLinkRequest */
    MagicLinkRequest: {
      /**
       * Email
       * Format: email
       * @description Email address to send the magic link to
       */
      email: string
    }
    /** Memory */
    Memory: {
      /**
       * Title
       * @description Title of the memory
       */
      title: string
      /**
       * Content
       * @description Static memories to assign to characters
       */
      content: string
      /** Character Ids */
      character_ids: number[]
      /** Id */
      id: number
    }
    /** MemoryCreate */
    MemoryCreate: {
      /**
       * Title
       * @description Title of the memory
       */
      title: string
      /**
       * Content
       * @description Static memories to assign to characters
       */
      content: string
      /** Character Ids */
      character_ids: number[]
    }
    /** MemoryUpdate */
    MemoryUpdate: {
      /**
       * Title
       * @description Title of the memory
       */
      title: string
      /**
       * Content
       * @description Static memories to assign to characters
       */
      content: string
      /** Character Ids */
      character_ids: number[]
    }
    /**
     * ModifierLimits
     * @description Ability and skill modifier limits for player validation
     */
    ModifierLimits: {
      /**
       * Ability Min
       * @description Minimum ability modifier value
       */
      ability_min: number
      /**
       * Ability Max
       * @description Maximum ability modifier value
       */
      ability_max: number
      /**
       * Skill Min
       * @description Minimum skill modifier value
       */
      skill_min: number
      /**
       * Skill Max
       * @description Maximum skill modifier value
       */
      skill_max: number
    }
    /** Player */
    Player: {
      /**
       * Name
       * @description Player name
       */
      name: string
      /**
       * Rl Name
       * @description Real-life player name
       */
      rl_name: string
      /**
       * Appearance
       * @description Player appearance
       */
      appearance: string
      /**
       * Race
       * @description Player race
       */
      race: string
      /**
       * Class Name
       * @description Player class
       */
      class_name: string
      /**
       * Size
       * @description Player size
       */
      size: string
      /**
       * Alignment
       * @description Player alignment
       */
      alignment: string
      /**
       * Gender
       * @description Player gender
       */
      gender: string
      /**
       * Abilities
       * @description Abilities of the player
       */
      abilities: {
        [key: string]: number
      }
      /**
       * Skills
       * @description Skills of the player
       */
      skills: {
        [key: string]: number
      }
      /** Id */
      id: number
    }
    /** PlayerCreate */
    PlayerCreate: {
      /**
       * Name
       * @description Player name
       */
      name: string
      /**
       * Rl Name
       * @description Real-life player name
       */
      rl_name: string
      /**
       * Appearance
       * @description Player appearance
       */
      appearance: string
      /**
       * Race
       * @description Player race
       */
      race: string
      /**
       * Class Name
       * @description Player class
       */
      class_name: string
      /**
       * Size
       * @description Player size
       */
      size: string
      /**
       * Alignment
       * @description Player alignment
       */
      alignment: string
      /**
       * Gender
       * @description Player gender
       */
      gender: string
      /**
       * Abilities
       * @description Abilities of the player
       */
      abilities: {
        [key: string]: number
      }
      /**
       * Skills
       * @description Skills of the player
       */
      skills: {
        [key: string]: number
      }
    }
    /**
     * PlayerEncounterResponse
     * @description Simplified encounter response for player view
     */
    PlayerEncounterResponse: {
      /** Id */
      id: number
      /**
       * Name
       * @description Encounter name
       */
      name: string
      /**
       * Description
       * @description Encounter description
       */
      description?: string | null
      /**
       * World Id
       * @description World ID this encounter belongs to
       */
      world_id: number
      /**
       * Characters
       * @description Characters in this encounter
       */
      characters?: components['schemas']['Character'][]
    }
    /** PlayerLoginResponse */
    PlayerLoginResponse: {
      /**
       * Login Url
       * @description The login URL for the player
       */
      login_url: string
      /**
       * Expires At
       * Format: date-time
       * @description When this login link expires
       */
      expires_at: string
    }
    /**
     * PlayerUpdate
     * @description Player update model - all fields optional with same validation rules.
     */
    PlayerUpdate: {
      /** Name */
      name?: string | null
      /** Rl Name */
      rl_name?: string | null
      /** Appearance */
      appearance?: string | null
      /** Race */
      race?: string | null
      /** Class Name */
      class_name?: string | null
      /** Size */
      size?: string | null
      /** Alignment */
      alignment?: string | null
      /** Gender */
      gender?: string | null
      /** Abilities */
      abilities?: {
        [key: string]: number
      } | null
      /** Skills */
      skills?: {
        [key: string]: number
      } | null
    }
    /** Reveal */
    Reveal: {
      /**
       * Title
       * @description Reveal title
       */
      title: string
      /** Character Ids */
      character_ids: number[]
      /**
       * Level 1 Content
       * @description Standard reveal content
       */
      level_1_content: string
      /**
       * Level 2 Content
       * @description Privileged reveal content
       */
      level_2_content?: string | null
      /**
       * Level 3 Content
       * @description Exclusive reveal content
       */
      level_3_content?: string | null
      /**
       * Standard Threshold
       * @description Reveal threshold
       * @default 0
       */
      standard_threshold: number
      /**
       * Privileged Threshold
       * @description Reveal threshold
       * @default 15
       */
      privileged_threshold: number
      /**
       * Exclusive Threshold
       * @description Reveal threshold
       * @default 20
       */
      exclusive_threshold: number
      /** Id */
      id: number
    }
    /** RevealCreate */
    RevealCreate: {
      /**
       * Title
       * @description Reveal title
       */
      title: string
      /** Character Ids */
      character_ids: number[]
      /**
       * Level 1 Content
       * @description Standard reveal content
       */
      level_1_content: string
      /**
       * Level 2 Content
       * @description Privileged reveal content
       */
      level_2_content?: string | null
      /**
       * Level 3 Content
       * @description Exclusive reveal content
       */
      level_3_content?: string | null
      /**
       * Standard Threshold
       * @description Reveal threshold
       * @default 0
       */
      standard_threshold: number
      /**
       * Privileged Threshold
       * @description Reveal threshold
       * @default 15
       */
      privileged_threshold: number
      /**
       * Exclusive Threshold
       * @description Reveal threshold
       * @default 20
       */
      exclusive_threshold: number
    }
    /** RevealUpdate */
    RevealUpdate: {
      /** Title */
      title?: string | null
      /** Character Ids */
      character_ids?: number[] | null
      /** Level 1 Content */
      level_1_content?: string | null
      /** Level 2 Content */
      level_2_content?: string | null
      /** Level 3 Content */
      level_3_content?: string | null
      /** Standard Threshold */
      standard_threshold?: number | null
      /** Privileged Threshold */
      privileged_threshold?: number | null
      /** Exclusive Threshold */
      exclusive_threshold?: number | null
    }
    /**
     * SizeOptions
     * @description Size options for different entity types
     */
    SizeOptions: {
      /**
       * Player
       * @description Valid sizes for players
       */
      player: string[]
      /**
       * Character
       * @description Valid sizes for characters
       */
      character: string[]
    }
    /**
     * ThresholdLimits
     * @description Threshold configuration limits for reveals
     */
    ThresholdLimits: {
      /**
       * Min
       * @description Minimum threshold value
       */
      min: number
      /**
       * Max
       * @description Maximum threshold value
       */
      max: number
      /**
       * Step
       * @description Step increment for threshold values
       */
      step: number
      /**
       * Min Gap
       * @description Minimum gap between threshold levels
       */
      min_gap: number
    }
    /** UserBillingBase */
    UserBillingBase: {
      /**
       * User Id
       * @description User ID tied to this billing summary
       */
      user_id: number
      /**
       * Available Tokens
       * @description Current available token balance
       */
      available_tokens: number
      /**
       * Last Used Tokens
       * @description Last persisted usage baseline
       */
      last_used_tokens: number
      /**
       * Total Used Tokens
       * @description Total lifetime token usage
       */
      total_used_tokens: number
    }
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
      /** Input */
      input?: unknown
      /** Context */
      ctx?: Record<string, never>
    }
    /**
     * ValidationLimits
     * @description Character and text limits for form validation
     */
    ValidationLimits: {
      /**
       * Name
       * @description Character name limit
       */
      name: number
      /**
       * Player Appearance
       * @description Player appearance description limit
       */
      player_appearance: number
      /**
       * Character Profession
       * @description Character profession limit
       */
      character_profession: number
      /**
       * Character Background
       * @description Character background limit
       */
      character_background: number
      /**
       * Character Communication
       * @description Character communication style limit
       */
      character_communication: number
      /**
       * Character Motivation
       * @description Character motivation limit
       */
      character_motivation: number
      /**
       * Memory Title
       * @description Memory title limit
       */
      memory_title: number
      /**
       * Memory Content
       * @description Memory content limit
       */
      memory_content: number
      /**
       * Reveal Title
       * @description Reveal title limit
       */
      reveal_title: number
      /**
       * Reveal Content
       * @description Reveal content limit
       */
      reveal_content: number
    }
    /**
     * Voice
     * @description Simplified voice model for frontend display
     */
    Voice: {
      /**
       * Voice Id
       * @description Voice ID
       */
      voice_id: string
      /**
       * Name
       * @description Voice name
       */
      name: string
      /**
       * Description
       * @description Voice description
       */
      description: string | null
      /**
       * Category
       * @description Voice category
       */
      category: string
      /** @description Voice labels */
      labels?: components['schemas']['VoiceLabels'] | null
    }
    /**
     * VoiceLabels
     * @description Voice labels for additional metadata
     */
    VoiceLabels: {
      /**
       * Gender
       * @description Voice gender
       */
      gender?: string | null
      /**
       * Accent
       * @description Voice accent
       */
      accent?: string | null
      /**
       * Descriptive
       * @description Descriptive label
       */
      descriptive?: string | null
      /**
       * Age
       * @description Voice age
       */
      age?: string | null
      /**
       * Language
       * @description Voice language
       */
      language?: string | null
      /**
       * Use Case
       * @description Voice use case
       */
      use_case?: string | null
    }
    /**
     * VoicesResponse
     * @description Response model for voices search with pagination
     */
    VoicesResponse: {
      /**
       * Voices
       * @description List of available voices
       */
      voices: components['schemas']['Voice'][] | null
      /**
       * Has More
       * @description Whether there are more voices available
       */
      has_more: boolean
      /**
       * Next Page Token
       * @description Token for next page
       */
      next_page_token?: string | null
      /**
       * Total Count
       * @description Total available voices
       */
      total_count?: number
    }
    /**
     * World
     * @description Complete world model with id, user_id and created_at
     */
    World: {
      /** Id */
      id: number
      /** User Id */
      user_id: number
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  request_magic_link_api_auth_request_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['MagicLinkRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  consume_magic_link_api_auth_get: {
    parameters: {
      query: {
        token: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  check_auth_api_auth_check_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AuthCheckResponse']
        }
      }
    }
  }
  logout_api_auth_logout_post: {
    parameters: {
      query?: never
      header?: {
        'x-world-id'?: string
      }
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_profile_api_profile_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserBillingBase']
        }
      }
    }
  }
  get_players_api_players_get: {
    parameters: {
      query?: never
      header?: {
        'x-world-id'?: string
      }
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Player'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  create_player_api_players_post: {
    parameters: {
      query?: never
      header?: {
        'x-world-id'?: string
      }
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PlayerCreate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Player']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_player_api_players__player_id__get: {
    parameters: {
      query?: never
      header?: {
        'x-world-id'?: string
      }
      path: {
        player_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Player']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  update_player_api_players__player_id__put: {
    parameters: {
      query?: never
      header?: {
        'x-world-id'?: string
      }
      path: {
        player_id: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PlayerUpdate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Player']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  delete_player_api_players__player_id__delete: {
    parameters: {
      query?: never
      header?: {
        'x-world-id'?: string
      }
      path: {
        player_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  consume_player_login_api_players__player_id__login_get: {
    parameters: {
      query: {
        token: string
      }
      header?: never
      path: {
        player_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  request_player_login_api_players__player_id__login_post: {
    parameters: {
      query?: never
      header?: {
        'x-world-id'?: string
      }
      path: {
        player_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PlayerLoginResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_player_encounter_api_players__player_id__encounter_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        player_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PlayerEncounterResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_characters_api_characters_get: {
    parameters: {
      query?: never
      header?: {
        'x-world-id'?: string
      }
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Character'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  create_character_api_characters_post: {
    parameters: {
      query?: never
      header?: {
        'x-world-id'?: string
      }
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CharacterCreate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Character']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_character_api_characters__character_id__get: {
    parameters: {
      query?: never
      header?: {
        'x-world-id'?: string
      }
      path: {
        character_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Character']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  update_character_api_characters__character_id__put: {
    parameters: {
      query?: never
      header?: {
        'x-world-id'?: string
      }
      path: {
        character_id: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CharacterUpdate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Character']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  delete_character_api_characters__character_id__delete: {
    parameters: {
      query?: never
      header?: {
        'x-world-id'?: string
      }
      path: {
        character_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_all_memories_api_memories_get: {
    parameters: {
      query?: never
      header?: {
        'x-world-id'?: string
      }
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Memory'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  create_memory_api_memories_post: {
    parameters: {
      query?: never
      header?: {
        'x-world-id'?: string
      }
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['MemoryCreate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Memory']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_memory_api_memories__memory_id__get: {
    parameters: {
      query?: never
      header?: {
        'x-world-id'?: string
      }
      path: {
        memory_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Memory']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  update_memory_api_memories__memory_id__put: {
    parameters: {
      query?: never
      header?: {
        'x-world-id'?: string
      }
      path: {
        memory_id: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['MemoryUpdate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Memory']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  delete_memory_api_memories__memory_id__delete: {
    parameters: {
      query?: never
      header?: {
        'x-world-id'?: string
      }
      path: {
        memory_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_all_reveals_api_reveals_get: {
    parameters: {
      query?: never
      header?: {
        'x-world-id'?: string
      }
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Reveal'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  create_reveal_api_reveals_post: {
    parameters: {
      query?: never
      header?: {
        'x-world-id'?: string
      }
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['RevealCreate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Reveal']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_reveal_api_reveals__reveal_id__get: {
    parameters: {
      query?: never
      header?: {
        'x-world-id'?: string
      }
      path: {
        reveal_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Reveal']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  update_reveal_api_reveals__reveal_id__put: {
    parameters: {
      query?: never
      header?: {
        'x-world-id'?: string
      }
      path: {
        reveal_id: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['RevealUpdate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Reveal']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  delete_reveal_api_reveals__reveal_id__delete: {
    parameters: {
      query?: never
      header?: {
        'x-world-id'?: string
      }
      path: {
        reveal_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_character_reveals_api_reveals_character__character_id__get: {
    parameters: {
      query?: never
      header?: {
        'x-world-id'?: string
      }
      path: {
        character_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Reveal'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_encounter_api_encounters__encounter_id__get: {
    parameters: {
      query?: never
      header?: {
        'x-world-id'?: string
      }
      path: {
        encounter_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Encounter']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  update_encounter_api_encounters__encounter_id__put: {
    parameters: {
      query?: never
      header?: {
        'x-world-id'?: string
      }
      path: {
        encounter_id: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['EncounterUpdate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Encounter']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  delete_encounter_api_encounters__encounter_id__delete: {
    parameters: {
      query?: never
      header?: {
        'x-world-id'?: string
      }
      path: {
        encounter_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  create_encounter_api_encounters__post: {
    parameters: {
      query?: never
      header?: {
        'x-world-id'?: string
      }
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['EncounterCreate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Encounter']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  create_connection_api_encounters_connections_post: {
    parameters: {
      query?: never
      header?: {
        'x-world-id'?: string
      }
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ConnectionCreate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Connection']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  update_connection_api_encounters_connections__connection_id__put: {
    parameters: {
      query?: never
      header?: {
        'x-world-id'?: string
      }
      path: {
        connection_id: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ConnectionUpdate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Connection']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  delete_connection_api_encounters_connections__connection_id__delete: {
    parameters: {
      query?: never
      header?: {
        'x-world-id'?: string
      }
      path: {
        connection_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_encounter_connections_api_encounters__encounter_id__connections_get: {
    parameters: {
      query?: never
      header?: {
        'x-world-id'?: string
      }
      path: {
        encounter_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Connection'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_conversation_data_api_encounters__encounter_id__conversation__player_id___character_id__get: {
    parameters: {
      query?: never
      header?: {
        'x-world-id'?: string
      }
      path: {
        encounter_id: number
        player_id: number
        character_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ConversationData']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_canvas_api_canvas_get: {
    parameters: {
      query?: never
      header?: {
        'x-world-id'?: string
      }
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CanvasResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  save_canvas_api_canvas_post: {
    parameters: {
      query?: never
      header?: {
        'x-world-id'?: string
      }
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CanvasSaveRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CanvasResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_game_data_api_game__get: {
    parameters: {
      query?: never
      header?: {
        'x-world-id'?: string
      }
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GameDataResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_tts_providers_api_voices_tts_providers_get: {
    parameters: {
      query?: never
      header?: {
        'x-world-id'?: string
      }
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': string[]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  search_voices_api_voices_search_get: {
    parameters: {
      query: {
        /** @description Search term for voices */
        search_term: string
        /** @description Pagination token for next page */
        next_page_token?: string | null
        /** @description TTS provider */
        tts_provider: string
      }
      header?: {
        'x-world-id'?: string
      }
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['VoicesResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_voice_sample_api_voices__voice_id__sample_get: {
    parameters: {
      query: {
        /** @description TTS provider */
        tts_provider: string
      }
      header?: {
        'x-world-id'?: string
      }
      path: {
        voice_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_worlds_api_worlds_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['World'][]
        }
      }
    }
  }
  create_world_api_worlds_post: {
    parameters: {
      query?: never
      header?: {
        'x-world-id'?: string
      }
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['World']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_world_api_worlds__world_id__get: {
    parameters: {
      query?: never
      header?: {
        'x-world-id'?: string
      }
      path: {
        world_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['World']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  delete_world_api_worlds__world_id__delete: {
    parameters: {
      query?: never
      header?: {
        'x-world-id'?: string
      }
      path: {
        world_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
}
