# Common field limits
NAME_LIMIT = 100
TITLE_LIMIT = 200

# Player limits
PLAYER_APPEARANCE_MAX_LIMIT = 500

# Character limits
CHARACTER_BACKGROUND_LIMIT = 500
CHARACTER_COMMUNICATION_LIMIT = 300
CHARACTER_MOTIVATION_LIMIT = 300
CHARACTER_PROFESSION_LIMIT = 100
PREFERENCE_VALUE_MIN = -5  # -VERY_EASY
PREFERENCE_VALUE_MAX = 5  # VERY_EASY

# Memory limits
MEMORY_TITLE_LIMIT = 200
MEMORY_CONTENT_LIMIT = 1000

# Reveal limits
REVEAL_TITLE_LIMIT = 200
REVEAL_CONTENT_LIMIT = 700

# Encounter limits
ENCOUNTER_NAME_LIMIT = 100
ENCOUNTER_DESCRIPTION_LIMIT = 1000

# Connection limits
CONNECTION_HANDLE_LIMIT = 10  # "top", "right", "bottom", "left"
CONNECTION_EDGE_TYPE_LIMIT = 10  # "straight", "smoothstep", "step", "bezier"
CONNECTION_COLOR_LIMIT = 7  # "#007bff" format
