# Common field limits
NAME_LIMIT = 30
TITLE_LIMIT = 30
DESCRIPTION_LIMIT = 300

# Player limits
PLAYER_APPEARANCE_MAX_LIMIT = DESCRIPTION_LIMIT

# Character limits
CHARACTER_BACKGROUND_LIMIT = 500
CHARACTER_COMMUNICATION_LIMIT = DESCRIPTION_LIMIT
CHARACTER_MOTIVATION_LIMIT = DESCRIPTION_LIMIT
CHARACTER_PROFESSION_LIMIT = NAME_LIMIT
PREFERENCE_VALUE_MIN = -5  # -VERY_EASY
PREFERENCE_VALUE_MAX = 5  # VERY_EASY

# Memory limits
MEMORY_CONTENT_LIMIT = 1000

# Reveal limits
REVEAL_CONTENT_LIMIT = 700

# Encounter limits
ENCOUNTER_DESCRIPTION_LIMIT = 500

# Connection limits
CONNECTION_HANDLE_LIMIT = 10  # "top", "right", "bottom", "left"
CONNECTION_EDGE_TYPE_LIMIT = 10  # "straight", "smoothstep", "step", "bezier"
CONNECTION_COLOR_LIMIT = 7  # "#007bff" format
